version: 2
updates:
  - package-ecosystem: "npm"
    labels:
      - 📦 dependencies
    directory: "/server" # location of package.json
    commit-message:
      prefix: "chore(deps)"
    schedule:
      interval: "daily"
