name: 🐞 Bug Report
description: Report a bug found in the Opentek source code
labels: ["bug", "gssoc23"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable (recommended)
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browser are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: checkboxes
    id: no-duplicate-checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the [existing issues](https://github.com/Opentek-Org/opentek/issues)"
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/Opentek-Org/opentek/blob/main/CONTRIBUTING.md)"
          required: true

        - label: "I want to work on this issue. (optional)"
          required: false

        - label: "I am a GSSoC'23 contributor"
          required: false

  - type: markdown
    attributes:
      value: |
        You can also join the Discord community [here](https://discord.gg/9qyr4Mdc3Y)
        Feel free to check out other amazing repositories of the Opentek [here](https://github.com/Opentek-Org)
