name: ✨ Feature Request
description: Suggest a feature request
title: '[Feat]: '
labels:
  - '⭐ goal: addition'
body:
  - type: textarea
    id: what-feature
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: Describe it in detail
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-content
    attributes:
      label: Additional context.
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Show us the magic with screenshots
      placeholder: Attach screenshots to visualize your idea
    validations:
      required: false

